packages:
  - client
  - server

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
<<<<<<< HEAD
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - unrs-resolver
  - workerd
=======
  - core-js
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
>>>>>>> origin/main-final
